/** @type {import('tailwindcss').Config} */
export default {
  content: ['./index.html', './src/**/*.{js,ts,jsx,tsx}'],
  darkMode: 'class',
  theme: {
    extend: {
      colors: {
        'on-primary-fixed-variant': '#402bb7',
        'error': '#ba1a1a',
        'surface-dim': '#dadada',
        'secondary-container': '#fd583b',
        'on-tertiary-fixed-variant': '#782f30',
        'on-primary-fixed': '#160066',
        'surface-container-low': '#f3f3f3',
        'on-error': '#ffffff',
        'on-tertiary-fixed': '#3e0409',
        'outline': '#787585',
        'secondary-fixed-dim': '#ffb4a5',
        'on-secondary-fixed-variant': '#8f1100',
        'on-surface': '#1b1b1b',
        'surface-container-lowest': '#ffffff',
        'surface-container': '#eeeeee',
        'on-primary': '#ffffff',
        'tertiary-fixed-dim': '#ffb3b1',
        'on-background': '#1b1b1b',
        'tertiary-fixed': '#ffdad8',
        'surface-bright': '#f9f9f9',
        'primary-container': '#6a5be2',
        'surface': '#f9f9f9',
        'tertiary-container': '#ab5656',
        'background': '#f9f9f9',
        'surface-container-highest': '#e2e2e2',
        'secondary-fixed': '#ffdad3',
        'on-tertiary-container': '#fff1f0',
        'secondary': '#b6250d',
        'error-container': '#ffdad6',
        'tertiary': '#8d3f3f',
        'inverse-surface': '#303030',
        'on-error-container': '#93000a',
        'on-secondary-container': '#590700',
        'on-secondary': '#ffffff',
        'on-tertiary': '#ffffff',
        'surface-container-high': '#e8e8e8',
        'inverse-primary': '#c6bfff',
        'outline-variant': '#c8c4d6',
        'inverse-on-surface': '#f1f1f1',
        'on-secondary-fixed': '#3f0400',
        'on-primary-container': '#f7f2ff',
        'surface-tint': '#5848cf',
        'primary': '#5140c8',
        'primary-fixed-dim': '#c6bfff',
        'surface-variant': '#e2e2e2',
        'on-surface-variant': '#474554',
        'primary-fixed': '#e4dfff',
      },
      borderRadius: {
        DEFAULT: '0.5rem',
        lg: '0.75rem',
        xl: '1.5rem',
        '2xl': '2rem',
        '4xl': '2.5rem',
        full: '9999px',
      },
      fontFamily: {
        headline: ['Inter', 'sans-serif'],
        body: ['Inter', 'sans-serif'],
        label: ['Inter', 'sans-serif'],
        mono: ['"Source Code Pro"', 'monospace'],
      },
      boxShadow: {
        cloud: '0 12px 24px rgba(27, 27, 27, 0.04)',
        'cloud-md': '0 20px 40px rgba(81, 64, 200, 0.12)',
      },
      animation: {
        marquee: 'marquee 40s linear infinite',
        spin: 'spin 4s linear infinite',
      },
      keyframes: {
        marquee: {
          '0%': { transform: 'translateX(0)' },
          '100%': { transform: 'translateX(-50%)' },
        },
      },
    },
  },
  plugins: [],
};
