import { jsPDF } from 'jspdf';

/**
 * Generates and downloads a styled PDF risk report.
 * @param {Object} data - Report data from AI and metrics
 */
export function downloadPDFReport({ title, symbol, reportText, metrics, generatedAt }) {
  const doc = new jsPDF({ unit: 'mm', format: 'a4' });
  const W = doc.internal.pageSize.getWidth();
  const margin = 20;
  const contentWidth = W - margin * 2;
  let y = 0;

  // ── Header Banner ──────────────────────────────────────────────
  doc.setFillColor(81, 64, 200); // primary color
  doc.rect(0, 0, W, 38, 'F');

  doc.setTextColor(255, 255, 255);
  doc.setFontSize(22);
  doc.setFont('helvetica', 'bold');
  doc.text('RiskCanvas', margin, 16);

  doc.setFontSize(10);
  doc.setFont('helvetica', 'normal');
  doc.text('AI-Powered Financial Risk Analysis', margin, 24);
  doc.text(`Generated: ${generatedAt || new Date().toLocaleString()}`, margin, 31);

  // Risk label badge (right)
  doc.setFillColor(106, 91, 226);
  doc.roundedRect(W - margin - 50, 8, 50, 22, 3, 3, 'F');
  doc.setFontSize(9);
  doc.text('RISK REPORT', W - margin - 25, 19, { align: 'center' });
  doc.setFontSize(13);
  doc.setFont('helvetica', 'bold');
  doc.text(symbol?.toUpperCase() || 'PORTFOLIO', W - margin - 25, 27, { align: 'center' });

  y = 50;

  // ── Title ──────────────────────────────────────────────────────
  doc.setTextColor(27, 27, 27);
  doc.setFontSize(16);
  doc.setFont('helvetica', 'bold');
  doc.text(title || 'Risk Analysis Report', margin, y);
  y += 12;

  // ── Metrics Grid ───────────────────────────────────────────────
  if (metrics && Object.keys(metrics).length > 0) {
    doc.setFontSize(11);
    doc.setFont('helvetica', 'bold');
    doc.setTextColor(81, 64, 200);
    doc.text('KEY METRICS', margin, y);
    y += 6;

    // Light box background
    doc.setFillColor(244, 240, 255);
    doc.roundedRect(margin, y, contentWidth, 30, 3, 3, 'F');

    const entries = Object.entries(metrics);
    const cols = Math.min(entries.length, 4);
    const cellW = contentWidth / cols;

    doc.setTextColor(71, 69, 84);
    doc.setFontSize(8);
    doc.setFont('helvetica', 'normal');
    entries.slice(0, 4).forEach(([key, val], i) => {
      const cx = margin + i * cellW + cellW / 2;
      doc.setFont('helvetica', 'bold');
      doc.setFontSize(12);
      doc.setTextColor(27, 27, 27);
      doc.text(String(val), cx, y + 13, { align: 'center' });
      doc.setFont('helvetica', 'normal');
      doc.setFontSize(7);
      doc.setTextColor(113, 117, 133);
      doc.text(key.toUpperCase(), cx, y + 21, { align: 'center' });
    });
    y += 38;
  }

  // ── AI Report Text ─────────────────────────────────────────────
  doc.setFontSize(11);
  doc.setFont('helvetica', 'bold');
  doc.setTextColor(81, 64, 200);
  doc.text('AI ANALYSIS', margin, y);
  y += 7;

  doc.setFont('helvetica', 'normal');
  doc.setFontSize(10);
  doc.setTextColor(27, 27, 27);

  const lines = doc.splitTextToSize(reportText || 'No analysis generated.', contentWidth);
  // Section-aware coloring
  lines.forEach((line) => {
    if (y > 270) { doc.addPage(); y = 20; }
    const isSectionHeader = /^\d+\.\s+[A-Z\s]+$/.test(line.trim());
    if (isSectionHeader) {
      doc.setFont('helvetica', 'bold');
      doc.setTextColor(81, 64, 200);
      y += 4;
    } else {
      doc.setFont('helvetica', 'normal');
      doc.setTextColor(27, 27, 27);
    }
    doc.text(line, margin, y);
    y += 6;
  });

  // ── Disclaimer ─────────────────────────────────────────────────
  if (y > 255) { doc.addPage(); y = 20; }
  y += 10;
  doc.setFillColor(242, 242, 242);
  doc.roundedRect(margin, y, contentWidth, 16, 2, 2, 'F');
  doc.setFontSize(7.5);
  doc.setTextColor(113, 117, 133);
  doc.text(
    'DISCLAIMER: This report is generated by AI for educational purposes only. It does not constitute financial advice.',
    margin + 4, y + 6
  );
  doc.text('Past performance is not indicative of future results. Always consult a certified financial advisor.', margin + 4, y + 12);

  // ── Footer ─────────────────────────────────────────────────────
  doc.setFontSize(8);
  doc.setTextColor(81, 64, 200);
  doc.text('RiskCanvas — Architectural Financial Education', W / 2, 290, { align: 'center' });

  const filename = `RiskCanvas_Report_${symbol || 'Portfolio'}_${Date.now()}.pdf`;
  doc.save(filename);
}
